sudo: required
language: ruby
rvm:
  - 2.3.1
services:
  - docker

script:
  - true
  - travis/continuous_deployment

# the call to 'travis/continuous_deployment' above is temporary.  It
# aim at testing continuous_deployment from within a PR.  It's needed since
# Travis doesn't allow to run a 'deploy:' action from a PR. ( or I didn't find
# how to )

deploy:
  provider: script
  script: travis/continuous_deployment
  on:
    branch: master
    repo: Liaison-Intl/upgrade_toolbelt

# Notice that failure happening in after_script or after_success doesn't fail
# the build which make it problematic to implement continuous deployment purely
# within .travis.yml. Thus the usage of the deploy script above.
#
# https://github.com/travis-ci/travis-ci/issues/758
# https://docs.travis-ci.com/user/customizing-the-build
