FROM alpine:3.4

RUN apk add --no-cache \
    ruby=2.3.1-r0 \
    ruby-dev=2.3.1-r0 \
    build-base=0.4-r1 \
    libffi-dev=3.2.1-r2 \
    ruby-irb=2.3.1-r0 \
    ca-certificates

RUN update-ca-certificates

RUN echo 'gem: --no-rdoc --no-ri' >> /etc/gemrc && \
    gem install \
    bundler \
    rdoc \
    io-console

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN bundle install

COPY . .

WORKDIR lib/ci/

CMD ./bin/rails_upgrade_analyzer
