version: '2'

services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile.travis_analyzer
    command: /opt/ci/bin/travis_analyzer --listen
    env_file:
      - ./kv.conf
    volumes:
      - .:/opt/ci

