#!/bin/bash

### On any error the script will fail
set -xeo pipefail

### Install dependancy
export CLOUDSDK_CORE_DISABLE_PROMPTS=1

# If the SDK is not already cached, download it and unpack it
if [ ! -d ${HOME}/google-cloud-sdk ]; then
  curl https://sdk.cloud.google.com | bash || true;
fi

source /home/travis/.bashrc
export PATH=/home/travis/google-cloud-sdk/bin:$PATH
gcloud components update kubectl
gcloud --version

### Authenticate to gcloud
export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gce.json # ENV var used by kubectl
set +x # Prevent exposure of GCE_JSON_KEY in travis output
  echo ${GCE_JSON_KEY} > $GOOGLE_APPLICATION_CREDENTIALS
set -x
gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}

### Push container to GCR registry
gcloud docker -- push gcr.io/${GCE_PROJECT}/ci:${TRAVIS_BUILD_NUMBER}

### Fetch GKE credential
gcloud container clusters get-credentials ${GKE_CLUSTER_NAME} --project ${GCE_PROJECT} --zone ${GCE_ZONE}

### Update 'deployment' object in GKE which trigger a rollout of the new images
kubectl set image deployment/upgrade-analyzer-deployment upgrade-analyzer=gcr.io/${GCE_PROJECT}/ci:${TRAVIS_BUILD_NUMBER}
